In [3]:
import json
import pandas as pd

base_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI"
json_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_EEG\sub-001\eeg\sub-001_task-fmrirestingec_eeg.json"
tsv_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_EEG\sub-001\eeg\sub-001_task-fmrirestingec_channels.tsv"
with open(json_path, "r", encoding="utf-8") as f:
    meta = json.load(f)

print("Metadatos JSON:")
for k, v in meta.items():
    print(f"{k}: {v}")

Metadatos JSON:
ECGChannelCount: 1
EEGChannelCount: 32
EEGReference: Cz
EMGChannelCount: 0
EOGChannelCount: 0
EpochLength: 639.32
InstitutionAddress: Blvd. Juriquilla 3001, Juriquilla, Santiago de Queretaro, Queretaro, 76230, Mexico
InstitutionName: Universidad Nacional Autonoma de Mexico
InstitutionalDepartmentName: Instituto de Neurobiologia
MiscChannelCount: 0
PowerLineFrequency: 60
RecordingDuration: 639.32
SamplingFrequency: 1000
SoftwareFilters: n/a
TaskDescription: Eyes closed and eyes open EEG data recorded outside the MR environment, inside the scanner without image acquisition and during simultaneous fMRI acquisition
TaskName: fmrirestingec
TriggerChannelCount: 0


In [4]:
channels = pd.read_csv(tsv_path, sep="\t")
print("\nCanales:")
print(channels.head())
print("\nTipos de canal:")
print(channels["type"].value_counts())


Canales:
    name type units  sampling_frequency  description  low_cutoff  high_cutoff  \
0  EEG 1  eeg    µV                1000          NaN         NaN          NaN   
1  EEG 2  eeg    µV                1000          NaN         NaN          NaN   
2  EEG 3  eeg    µV                1000          NaN         NaN          NaN   
3  EEG 4  eeg    µV                1000          NaN         NaN          NaN   
4  EEG 5  eeg    µV                1000          NaN         NaN          NaN   

   notch  software_filters  status  status_description  
0    NaN               NaN     NaN                 NaN  
1    NaN               NaN     NaN                 NaN  
2    NaN               NaN     NaN                 NaN  
3    NaN               NaN     NaN                 NaN  
4    NaN               NaN     NaN                 NaN  

Tipos de canal:
type
eeg    33
ecg     1
Name: count, dtype: int64


In [16]:
import mne

set_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_EEG\sub-001\eeg\sub-001_task-fmrieoec_eeg.set"
raw = mne.io.read_raw_eeglab(set_path, preload=True)

print(raw)
print(raw.info)
print(raw.ch_names)

Reading C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_EEG\sub-001\eeg\sub-001_task-fmrieoec_eeg.fdt
Reading 0 ... 444593  =      0.000 ...   444.593 secs...
<RawEEGLAB | sub-001_task-fmrieoec_eeg.fdt, 33 x 444594 (444.6 s), ~112.0 MiB, data loaded>
<Info | 8 non-empty values
 bads: []
 ch_names: E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, ...
 chs: 33 EEG
 custom_ref_applied: False
 dig: 36 items (3 Cardinal, 33 EEG)
 highpass: 0.0 Hz
 lowpass: 500.0 Hz
 meas_date: unspecified
 nchan: 33
 projs: []
 sfreq: 1000.0 Hz
>
['E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'E10', 'E11', 'E12', 'E13', 'E14', 'E15', 'E16', 'E17', 'E18', 'E19', 'E20', 'E21', 'E22', 'E23', 'E24', 'E25', 'E26', 'E27', 'E28', 'E29', 'E30', 'E31', 'E32', 'ECG']


C:\Users\pedro\AppData\Local\Temp\ipykernel_36180\388776091.py:4: RuntimeWarning: Data file name in EEG.data (01_EEG_fMRI_OCOA.fdt) is incorrect, the file name must have changed on disk, using the correct file name (sub-001_task-fmrieoec_eeg.fdt).
  raw = mne.io.read_raw_eeglab(set_path, preload=True)


In [14]:
for ch, typ in zip(raw.info['ch_names'], raw.get_channel_types()):
    print(ch, typ)

E1 eeg
E2 eeg
E3 eeg
E4 eeg
E5 eeg
E6 eeg
E7 eeg
E8 eeg
E9 eeg
E10 eeg
E11 eeg
E12 eeg
E13 eeg
E14 eeg
E15 eeg
E16 eeg
E17 eeg
E18 eeg
E19 eeg
E20 eeg
E21 eeg
E22 eeg
E23 eeg
E24 eeg
E25 eeg
E26 eeg
E27 eeg
E28 eeg
E29 eeg
E30 eeg
E31 eeg
E32 eeg
ECG eeg


In [6]:
mne.viz.set_browser_backend("qt")

raw.plot(
    n_channels=20,
    duration=10,
    show_scrollbars=True,
    block=True
)

Using qt as 2D backend.
Channels marked as bad:
none


Traceback (most recent call last):
  File "c:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\.venv\Lib\site-packages\matplotlib\cbook.py", line 361, in process
    func(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
TypeError: OrthoSlicer3D._cleanup() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "c:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\.venv\Lib\site-packages\matplotlib\cbook.py", line 361, in process
    func(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
TypeError: OrthoSlicer3D._cleanup() takes 1 positional argument but 2 were given


In [ ]:
from mne.preprocessing import ICA

raw.filter(l_freq=1.0, h_freq=40.0)
raw.notch_filter(freqs=50)

ica = ICA(n_components=20, random_state=97, max_iter="auto")
ica.fit(raw)

In [ ]:
ica.plot_sources(raw)
ica.plot_components()

In [8]:
%matplotlib qt

In [9]:
import nibabel as nib
from nibabel.viewers import OrthoSlicer3D
from nilearn import image

fmri_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_MRI\sub-001\ses-001\func\sub-001_ses-001_task-rest_bold.nii.gz"
anat_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_MRI\sub-001\ses-001\anat\sub-001_ses-001_acq-highres_T1w.nii.gz"

fmri_img = nib.load(fmri_path)
anat_img = nib.load(anat_path)

# Anatomica en ventana aparte
anat_viewer = OrthoSlicer3D(anat_img.get_fdata(), anat_img.affine)
anat_viewer.show()

# Volumen funcional t=0 en ventana aparte
vol0 = image.index_img(fmri_img, 0)
func_viewer = OrthoSlicer3D(vol0.get_fdata(), vol0.affine)
func_viewer.show()

In [ ]:
from interactive_fmri_viewer import launch_interactive_viewer

fmri_path = r"C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_MRI\sub-001\ses-001\func\sub-001_ses-001_task-rest_bold.nii.gz"
launch_interactive_viewer(fmri_path)

In [10]:
def describe_image(path: Path) -> nib.spatialimages.SpatialImage:
    img = nib.load(str(path))
    data = img.get_fdata(dtype=np.float32)
    header = img.header

    print(f"\n=== {path.name} ===")
    print(f"Ruta: {path}")
    print(f"Shape: {img.shape}")
    print(f"Affine:\n{img.affine}")
    print(f"Voxel size (mm): {header.get_zooms()}")
    print(f"Datatype: {header.get_data_dtype()}")
    print(f"Min/Max: {np.nanmin(data):.3f} / {np.nanmax(data):.3f}")

    if data.ndim == 4:
        mean_img = data.mean(axis=3)
        print(f"TR / pixdim[4]: {header.get_zooms()[3] if len(header.get_zooms()) > 3 else 'N/A'}")
        print(f"Volumenes: {data.shape[3]}")
        print(f"Media global: {np.nanmean(mean_img):.3f}")
        print(f"Std global: {np.nanstd(mean_img):.3f}")
    else:
        print(f"Media global: {np.nanmean(data):.3f}")
        print(f"Std global: {np.nanstd(data):.3f}")

    return img

In [12]:
from pathlib import Path
import numpy as np

fmri_path_describe = Path(fmri_path)
describe_image(fmri_path_describe)


=== sub-001_ses-001_task-rest_bold.nii.gz ===
Ruta: C:\Users\pedro\Documents\DOCTORADO_Pedro\Code\phD_Repository\data\raw\Dataset1\Simultaneous_EEG_fMRI\BIDS_dataset_MRI\sub-001\ses-001\func\sub-001_ses-001_task-rest_bold.nii.gz
Shape: (64, 64, 35, 300)
Affine:
[[ -4.           0.          -0.         126.78099823]
 [ -0.           4.          -0.         -94.60499573]
 [  0.           0.           4.         -43.32229996]
 [  0.           0.           0.           1.        ]]
Voxel size (mm): (np.float32(4.0), np.float32(4.0), np.float32(4.0), np.float32(2.0))
Datatype: int16
Min/Max: 0.000 / 4108.000
TR / pixdim[4]: 2.0
Volumenes: 300
Media global: 249.092
Std global: 588.471


In [ ]:
anat_path_describe = Path(anat_path)
describe_image(anat_path_describe)